config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
        resources :devices, only: [:show], param: :key do
          scope module: :devices do
            member do
              resources :touch, only: [:create]
              resources :version, only: [:create]
              resources :ads, only: [:index]
            end
          end

          resources :channels, only: [:show] do
            scope module: :channels do
              resources :programs, only: [:index]
            end
          end

        end
    end
  end

  namespace :admin do
    root 'admin/index#index'
    resources :devices

    resources :stores do
      scope module: :stores do
        resources :introductions, only: [:index, :create, :destroy]
      end
    end

    resources :ads do
      scope module: :ads do
        resources :files, only: [:create]
      end
    end

    resources :auditing_ads, only: [:index] do
      collection do
        post :batch_approve
      end
      scope module: :auditing_ads do
        member do
          resource :judgement, only: [:create, :destroy]
          resource :wait, only: [:create]
        end
      end
    end

    resources :channels do
      scope module: :channels do
        resources :programs, only: [:index, :update, :create, :destroy] do
          member do
            post :screenshot
            put :suspend
            put :recover
          end
          collection do
            put :rearrange
          end
        end
      end
    end

    resources :tmp_files
    resources :global_settings, only: [:index, :edit, :update]
  end


  resources :cities, only:[] do
    scope module: :cities do
      member do
        resources :areas, only:[:index]
      end
    end
  end
end

app/models/channel.rb
class Channel < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :programs
  # validations ...............................................................
  validates_presence_of :name
  # callbacks .................................................................
  # scopes ....................................................................
  scope :active, -> { where(is_active: true) }
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  def formated_api
    {
      id: self.id,
      name: self.name,
      icon: self.icon,
    }
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end

app/models/channel/age_group.rb
class Channel::AgeGroup < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :channel
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end

app/models/program.rb
class Program < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :channel
  belongs_to :current_screenshot, class_name: 'Screenshot', foreign_key: 'screenshot_id', optional: true
  has_many :screenshots, dependent: :destroy
  # validations ...............................................................
  validates_presence_of :name, :seconds, :video
  # callbacks .................................................................
  before_create do
    self.position ||= self.latest_position
  end

  after_create do
    Program::AutomaticSetVideoPlayTimeJob.perform_later(self.id)

    create_screenshots
  end

  # scopes ....................................................................
  scope :active, -> { where(is_active: true) }
  # additional config .........................................................
  mount_uploader :video, ProgramVideoUploader

  DEFAULT_VALUES = {
    seconds: 300,
    is_active: true
  }

  SCREENSHOT_TIMES = [1, 5 , 10 ,15, 20]
  # class methods .............................................................
  # public instance methods ...................................................
  def latest_position
    current_latest_record = self.class.where(channel_id: self.channel.id).order(position: :desc).take

    if current_latest_record
      current_latest_record.position + 1
    else
      1
    end
  end

  def swap_with! target
    self.position, target.position = target.position, self.position
    save and target.save
  end

  def suspend
    self.is_active = false
    self.position = nil
    save
  end

  def recover
    self.is_active = true
    self.position = latest_position
    save
  end

  def create_screenshots
    video_path = video.file.file
    SCREENSHOT_TIMES.each do |second|
      screenshot = ScreenshotService.new(video_path, second).perform
      self.screenshots.create image: File.open(screenshot.path)
      self.update_column(:screenshot_id, self.screenshots.first.id)
    end
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end

app/models/program/age_group.rb
class Program::AgeGroup < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :program
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end

app/models/program/screenshot.rb
class Program::Screenshot < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :program
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  mount_uploader :image, ImageUploader
  # class methods .............................................................
  # public instance methods ...................................................
  def formated_attributes
    {
      id: self.id,
      url: image.url
    }
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end

app/controllers/admin/channels/programs_controller.rb
class Admin::Channels::ProgramsController < Admin::AppsController

  skip_before_action :verify_authenticity_token

  def index
    @current_breadcrumb = { 'name' => '節目', 'link' => admin_channel_programs_path(params[:channel_id]) }
    channel = Channel.find params[:channel_id]
    @channel = channel
    @programs = ProgramSerializer.new(channel.programs.includes(:screenshots).order(:position))
      .serializable_hash[:data]
      .map { |hash| hash[:attributes] }
  end

  def create
    channel = Channel.find params[:channel_id]

    original_filename = params[:file].original_filename
    base_filename = File.basename(original_filename, File.extname(original_filename))

    program = channel.programs.build(
      video: params[:file],
      video_md5: Digest::MD5.hexdigest(params[:file].read),
      name: base_filename
    )

    if program.save
      resopnse_file = ProgramSerializer.new(program).serializable_hash
      render json: {
        program: resopnse_file[:data][:attributes].to_json
      }, status: :ok
    else
      render json: { errors: program.errors.full_messages.last }, status: :unprocessable_entity
    end
  end

  def update
    channel = Channel.find params[:channel_id]
    program = channel.programs.find params[:id]

    program.update(program_params)
    render json: {}, status: :ok
  end

  def rearrange
    channel = Channel.find params[:channel_id]
    new_order = params[:ids]
    programs = channel.programs.active.to_a.compact

    rearranged_programs = new_order.map do |program_id|
      programs.find { |program| program.id == program_id }
    end

    rearranged_programs.compact.each_with_index.map do |program, position|
      program.position = position
      program.save!
    end

    render json: {}, status: :ok
  end

  def suspend
    channel = Channel.find params[:channel_id]
    channel.programs.find(params[:id]).suspend
    render json: {}, status: :ok
  end

  def recover
    channel = Channel.find params[:channel_id]
    channel.programs.find(params[:id]).recover
    render json: {}, status: :ok
  end

  def destroy
    channel = Channel.find params[:channel_id]
    channel.programs.find(params[:id]).destroy
    render json: {}, status: :ok
  end

  def screenshot
    program = Program.find(params[:id])
    screenshot = program.screenshots.build image: params[:file]

    screenshot.save
    program.update_column :screenshot_id, screenshot.id

    render json: screenshot.formated_attributes, status: :ok
  end

  private
  def program_params
    @program ||= ActionController::Parameters.new(
      JSON.parse(request.body.read).symbolize_keys
    ).permit(:name, :seconds, :screenshot_id, screenshot_ids: [])
  end

  def rearranged_params
    @rearranged ||= ActionController::Parameters.new(
      JSON.parse(request.body.read).symbolize_keys
    ).permit(:ids)
  end

end

app/controllers/admin/channels_controller.rb
class Admin::ChannelsController < Admin::AppsController

  include Crudable

  before_action only: [:index] do
    @sub_title = '頻道'
  end

  before_action only: [:new, :create, :edit, :update] do
    @icon_options = Settings.icons.map do |text, icon_class|
      [ text, icon_class, {'data-icon' => icon_class } ]
    end
  end

  def filter_columns
    ['name']
  end

  private

  def current_collection
    default_scope.includes(:programs)
  end

  def permitted_attributes
    [:name, :icon, :position, :is_active]
  end

end

app/controllers/api/v1/channels/programs_controller.rb
class Api::V1::Channels::ProgramsController < ApplicationController

  def index
    channel = Channel.find params[:channel_id]
    programs = channel.programs.active.includes(:current_screenshot)

    serialized_programs = Api::ProgramSerializer.new(programs).serializable_hash

    render json: serialized_programs[:data].map { |program| program[:attributes] }, status: 200
  end

end

app/helpers/api/v1/channels/programs_helper.rb
module Api::V1::Channels::ProgramsHelper
end

app/views/admin/channels/programs/index.html.erb
<input type="hidden" id="channel" name="channel_id" data-id="<%= @channel.id %>" data-programs="<%= @programs.to_json %>">
<div id="app" class="m-portlet__head">
  <div class="m-portlet__head-caption">
    <div class="m-portlet__head-title">
      <h3 class="m-portlet__head-text">
        <%= @channel.name %>
      </h3>
    </div>
  </div>
</div>
<div class="m-portlet__body">
  <div class="form-group">
    <div class="row m--margin-top-40">
      <div class="col-xl-10 offset-xl-1">
        <div class="m-form__section m-form__section--first">
          <div class="form-group m-form__group row">
            <label class="col-form-label col-lg-3 col-sm-12">
              <a href="#" class="m-nav-grid__item"></a>
              <i class="m-nav-grid__icon flaticon-file"></i>
              素材上傳區
            </label>
            <div class="col-lg-6 col-md-9 col-sm-12">
              <div class="m-dropzone dropzone dz-clickable" id="m-dropzone-one">
                <div class="m-dropzone__msg dz-message needsclick">
                  <h5>
                    請拖曳檔案或點擊上傳
                  </h5>
                  <p>允許格式: MP4 <br />檔案大小限制: 100MB</p>
                </div>
              </div>
            </div>
          </div>
        </div> <!--End m-form__section first -->
        <div class="m-separator m-separator--dashed m-separator--lg"></div>
        <div class="m-form__heading">
          <h5 class="m-form__heading-title">
            播放中
          </h5>
        </div>
        <div class="m-portlet__body">
          <!--begin: local Datatable -->
          <div class="m-section__content">
            <programs-table-vue :rows="programs" :channel="channelId" />
          </div>
        </div>

        <div class="m-separator m-separator--dashed m-separator--lg"></div>
        <div class="m-form__heading">
          <h5 class="m-form__heading-title">
            已下架
          </h5>
        </div>
        <div class="m-portlet__body">
          <!--begin: local Datatable -->
          <div class="m-section__content">
            <!--begin: Tab content -->
            <table class="table table-striped m-table">
              <thead>
                <tr>
                  <th width="35%">
                    名稱
                  </th>
                  <th width="10%">
                    秒數
                  </th>
                  <th width="10%">
                    預覽圖
                  </th>
                  <th width="25%">
                    下架時間
                  </th>
                  <th width="15%">
                    操作
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="program in inactivePrograms()">
                  <td>
                    <a :href="program.video_url" target="_blank">
                      {{program.name}}
                    </a>
                  </td>
                  <td v-html="program.seconds"></td>
                  <td>
                    <img :src="program.current_screenshot.url" alt="100%x200" style="width: 96px; height: 54px;" v-if="program.current_screenshot" />
                  </td>
                  <td v-html="program.updated_at"></td>
                  <td>
                    <button class="btn btn-secondary m-btn btn-sm m-btn--icon m-btn--icon-only mt-2" @click="recover(program.id)">
                      <i class="la la-reply"></i>
                    </button>
                    <button class="btn btn-secondary m-btn btn-sm m-btn--icon m-btn--icon-only mt-2"@click="destroy(program.id)">
                      <i class="la la-remove"></i>
                    </button>
                  </td>
                </tr>
                <tr v-if="inactivePrograms().length == 0">
                  <td colspan="5">no any programs</td>
                </tr>
              </tbody>
            </table>
            <!--end::tab 1 content-->
          </div> <!-- End m-section__content -->
        </div>

        <!--end: local Datatable -->
      </div><!--End m-portlet__body -->
    </div> <!--End row -->
    <div class="m-form__actions m-form__actions--solid">
      <div class="row m--align-left">
        <div class="col-lg-8">
          <%= link_to(admin_channels_path, class: 'btn btn-info') do %>
            <i class="la la-angle-left"></i> 上一頁
          <% end %>
        </div>
      </div>
    </div>
  </div><!--End form-group-->
</div><!--End form-group-->