config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
        resources :devices, only: [:show], param: :key do
          scope module: :devices do
            member do
              resources :touch, only: [:create]
              resources :version, only: [:create]
              resources :ads, only: [:index]
            end
          end

          resources :channels, only: [:show] do
            scope module: :channels do
              resources :programs, only: [:index]
            end
          end

        end
    end
  end

  namespace :admin do
    root 'admin/index#index'
    resources :devices

    resources :stores do
      scope module: :stores do
        resources :introductions, only: [:index, :create, :destroy]
      end
    end

    resources :ads do
      scope module: :ads do
        resources :files, only: [:create]
      end
    end

    resources :auditing_ads, only: [:index] do
      collection do
        post :batch_approve
      end
      scope module: :auditing_ads do
        member do
          resource :judgement, only: [:create, :destroy]
          resource :wait, only: [:create]
        end
      end
    end

    resources :channels do
      scope module: :channels do
        resources :programs, only: [:index, :update, :create, :destroy] do
          member do
            post :screenshot
            put :suspend
            put :recover
          end
          collection do
            put :rearrange
          end
        end
      end
    end

    resources :tmp_files
    resources :global_settings, only: [:index, :edit, :update]
  end


  resources :cities, only:[] do
    scope module: :cities do
      member do
        resources :areas, only:[:index]
      end
    end
  end
end

app/models/device.rb
class Device < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :store
  # validations ...............................................................
  validates_presence_of :name, :mac
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  delegate :name, to: :store, prefix: true
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end

app/models/device/app_version.rb
class Device::AppVersion < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :devices
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end

app/controllers/admin/devices_controller.rb
class Admin::DevicesController < Admin::AppsController

  include Crudable

  private
  def permitted_attributes
    [
      :name, :mac, :store_id, :test_mode, :note
    ]
  end

  def filter_columns
    ['name']
  end

end

app/controllers/api/v1/devices/ads_controller.rb
class Api::V1::Devices::AdsController < ApplicationController
  def index
    ads = Ad.running
    serialized_programs = Api::AdSerializer.new(ads).serializable_hash

    render json: serialized_programs[:data].map { |program| program[:attributes] }, status: 200
  end

end

app/controllers/api/v1/devices/touch_controller.rb
class Api::V1::Devices::TouchController < Api::V1::ApiController

  def create
    current_device.touch(:last_report_time)
    head :no_content
  end

end

app/controllers/api/v1/devices/version_controller.rb
class Api::V1::Devices::VersionController < Api::V1::ApiController

  def create
    app_version = ::Device::AppVersion.find_or_create_by number: device_params[:app_version]
    if current_device.update_column :app_version_id, app_version.id
      render json: {}, status: 200
    else
      render json: '新增失敗', status: 500
    end
  end

  private
  def device_params
    @storage ||= JSON.parse(request.body.read).symbolize_keys.slice(*[:app_version])
  end

end

app/controllers/api/v1/devices_controller.rb
class Api::V1::DevicesController < Api::V1::ApiController
  def show
    serialized_device = Api::DeviceLaunchSerializer.new(current_device).serializable_hash
    device_attributes = serialized_device[:data][:attributes]
    render json: device_attributes, status: 200
  end
end

app/helpers/admin/devices_helper.rb
module Admin::DevicesHelper
end

app/helpers/api/v1/devices/ads_helper.rb
module Api::V1::Devices::AdsHelper
end

app/helpers/api/v1/devices/touch_helper.rb
module Api::V1::Devices::TouchHelper
end

app/helpers/api/v1/devices/version_helper.rb
module Api::V1::Devices::VersionHelper
end

app/helpers/api/v1/devices_helper.rb
module Api::V1::DevicesHelper
end

app/views/admin/devices/_form.html.erb
<div class="m-portlet">
  <%= render partial: 'shared/form_head', locals: {
  title: @form_title, sub_title: @form_sub_title
  } %>

  <%= simple_form_for(
  [:admin, current_object],
  wrapper: :inline_form,
  html: { class: 'm-form m-form--fit m-form--label-align-right'}) do |f| %>
  <div class="m-portlet__body">
    <div class="m-form__section m-form__section--first">
      <div class="row">
        <div class="col-xl-10 offset-xl-1">
          <div class="form-group m-form__group row">
            <%= f.input :name,
            wrapper_html: { class: 'col-lg-6 col-md-9 col-sm-12' },
            label: label_with_icon("設備名稱", "la la-television") %>
            <%= f.input :mac,
            wrapper_html: { class: 'col-lg-6 col-md-9 col-sm-12' },
            label: label_with_icon("MAC", "la la-database") %>
          </div>

          <div class="form-group m-form__group row">
            <%= f.association :store,
            wrapper_html: { class: 'col-lg-6 col-md-9 col-sm-12' },
            label: label_with_icon("店家", "la la-home") %>
            <div class="col-lg-6 col-md-9 col-sm-12">
              <label>
                <i class="la la-warning"></i>
                測試模式
              </label>
              <div class="col-3">
                <label>
                <span class="m-switch m-switch--icon m-switch--info">
                  <%= f.check_box :test_mode, as: :boolean %>
                  <span></span>
                </label>
              </div>
            </div>
          </div>

          <% unless current_object.new_record? %>
          <div class="form-group m-form__group row">
            <div class="col-lg-6 col-md-9 col-sm-12">
              <label>
                <i class="la la-clock-o"></i>
                設備最後回報時間
              </label>
              <div class="col-lg-6 col-md-9 col-sm-12">
                <%= content_tag(:p, current_object.last_report_time.to_s, class:"static") %>
              </div>
            </div>
          </div>
          <% end %>

          <div class="form-group m-form__group row">
            <%= f.input :note,
            wrapper_html: { class: 'col-lg-12 col-md-12 col-sm-12' },
            label: label_with_icon("備註", "la la-sticky-note") %>
          </div>

        </div>
      </div>
    </div>
  </div>
  <%= render partial: 'shared/submit', locals: { f: f, cancel_path: admin_devices_path } %>
  <% end %>
</div>

app/views/admin/devices/_index_alert.html.erb
<div class="alert m-alert--default">
  <div class="m-alert__text">
    <span class="m--font-info m--font-boldest">
      <i class="flaticon-exclamation-1"></i>
      狀態說明:
    </span>
  </div>
  <div class="m-alert__text row">
    <div class="col-md-3">
      <span class="m-badge m-badge--success">1</span>
      &nbsp; 未滿10分無服務
    </div>
    <div class="col-md-3">
      <span class="m-badge m-badge--warning">2</span>
      &nbsp; 超過10分鐘，未滿3天無服務
    </div>
    <div class="col-md-3">
      <span class="m-badge m-badge--danger">3</span>
      &nbsp; 超過3天無服務
    </div>
  </div>
</div>