config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
        resources :devices, only: [:show], param: :key do
          scope module: :devices do
            member do
              resources :touch, only: [:create]
              resources :version, only: [:create]
              resources :ads, only: [:index]
            end
          end

          resources :channels, only: [:show] do
            scope module: :channels do
              resources :programs, only: [:index]
            end
          end

        end
    end
  end

  namespace :admin do
    root 'admin/index#index'
    resources :devices

    resources :stores do
      scope module: :stores do
        resources :introductions, only: [:index, :create, :destroy]
      end
    end

    resources :ads do
      scope module: :ads do
        resources :files, only: [:create]
      end
    end

    resources :auditing_ads, only: [:index] do
      collection do
        post :batch_approve
      end
      scope module: :auditing_ads do
        member do
          resource :judgement, only: [:create, :destroy]
          resource :wait, only: [:create]
        end
      end
    end

    resources :channels do
      scope module: :channels do
        resources :programs, only: [:index, :update, :create, :destroy] do
          member do
            post :screenshot
            put :suspend
            put :recover
          end
          collection do
            put :rearrange
          end
        end
      end
    end

    resources :tmp_files
    resources :global_settings, only: [:index, :edit, :update]
  end


  resources :cities, only:[] do
    scope module: :cities do
      member do
        resources :areas, only:[:index]
      end
    end
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="zh-Hant">
  <!-- begin::Head -->

  <head>
    <meta charset="utf-8" />
    <title>
      Solmate 魔鏡管理系統
    </title>
    <%= csrf_meta_tags %>

    <meta name="description" content="Focus media">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'admin', media: 'all' %>
    <%= javascript_include_tag 'admin' %>
    <link rel="shortcut icon" href="<%= asset_path('favicon.ico') %>" />
  </head>
  <!-- end::Head -->
  <!-- end::Body -->

  <body class="m-page--fluid m--skin- m-content--skin-light2 m-header--fixed m-header--fixed-mobile m-aside-left--enabled m-aside-left--skin-light m-aside-left--fixed m-aside-left--offcanvas m-aside-left--minimize m-brand--minimize m-footer--push m-aside--offcanvas-default"  >
    <%= render 'shared/flash' %>
    <!-- begin:: Page -->
    <div class="m-grid m-grid--hor m-grid--root m-page">
      <!-- BEGIN: Header -->
      <header class="m-grid__item m-header "  data-minimize-offset="200" data-minimize-mobile-offset="200" >
        <div class="m-container m-container--fluid m-container--full-height">
          <div class="m-stack m-stack--ver m-stack--desktop">
            <!-- BEGIN: Brand -->
        <div class="m-stack__item m-brand ">
          <div class="m-stack m-stack--ver m-stack--general">
            <div class="m-stack__item m-stack__item--middle m-brand__logo">
              <% link_to(admin_root_path, class: "m-brand__logo-wrapper") do %>
              <%= image_tag('logo.png') %>
              <% end %>
            </div>
            <div class="m-stack__item m-stack__item--middle m-brand__tools">
              <!-- BEGIN: Responsive Aside Left Menu Toggler -->
              <a href="javascript:;" id="m_aside_left_offcanvas_toggle" class="m-brand__icon m-brand__toggler m-brand__toggler--left m--visible-tablet-and-mobile-inline-block">
                <span></span>
              </a>
              <!-- END -->
              <!-- BEGIN: Responsive Header Menu Toggler -->
              <a id="m_aside_header_menu_mobile_toggle" href="javascript:;" class="m-brand__icon m-brand__toggler m--visible-tablet-and-mobile-inline-block">
                <span></span>
              </a>
              <!-- END -->
              <!-- BEGIN: Topbar Toggler -->
              <a id="m_aside_header_topbar_mobile_toggle" href="javascript:;" class="m-brand__icon m--visible-tablet-and-mobile-inline-block">
              </a>
              <!-- BEGIN: Topbar Toggler -->
            </div>
          </div>
        </div>
        <!-- END: Brand -->
        <div class="m-stack__item m-stack__item--fluid m-header-head" id="m_header_nav">
          <%= render partial: 'shared/breadcrumbs' %>
          <%= render partial: 'shared/topbar' %>
        </div>
          </div>
        </div>
      </header>
      <!-- END: Header -->
      <!-- begin::Body -->
      <div class="m-grid__item m-grid__item--fluid m-grid m-grid--ver-desktop m-grid--desktop m-body">
        <!-- BEGIN: Left Aside -->
        <button class="m-aside-left-close  m-aside-left-close--skin-light " id="m_aside_left_close_btn">
          <i class="la la-close"></i>
        </button>
        <div id="m_aside_left" class="m-grid__item  m-aside-left  m-aside-left--skin-light ">
          <%= render "shared/logo" %>
          <%= render "shared/menu" %>
        </div>
        <div class="m-aside-menu-overlay"></div>
        <!-- END: Left Aside -->
        <div class="m-grid__item m-grid__item--fluid m-wrapper" data-behavior="app">
          <div class="m-content">
            <div class="m-portlet m-portlet--mobile">
              <%= yield %>
            </div>
            <% if lookup_context.find_all("#{ request.params['controller'] }/_#{ request.params['action'] }_alert").any? %>
            <%= render partial: "#{ request.params['controller'] }/#{ request.params['action'] }_alert"  %>
            <% end %>
            <%= render "shared/scroll_top" %>
          </div>
        </div>
        <!-- end:: Body -->
      </div>

      <%= render partial: 'shared/copyright' %>
      <!-- end:: Page -->
      <!-- begin::Scroll Top -->
      <div class="m-scroll-top m-scroll-top--skin-top" data-toggle="m-scroll-top" data-scroll-offset="500" data-scroll-speed="300">
        <i class="la la-arrow-up"></i>
      </div>
      <!-- end::Scroll Top -->
      <%= javascript_pack_tag "#{ request.params['controller'] }/#{ action_name }" rescue '' %>
  </body>
  <!-- end::Body -->

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mirror</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>